"""Accessible server-rendered views for the run decision workspace."""
from __future__ import annotations

import html
from typing import Any


def e(v: Any)->str:return html.escape(str(v or ""),quote=True)
def shell(title:str, body:str, *, focus=False)->str:
    nav=''.join(f'<a href="{u}"{c}>{n}</a>' for n,u,c in [("Runs","/workspace/runs",' aria-current="page"' if title.startswith("Runs") else ''),("Baselines","/workspace/baselines",' aria-current="page"' if title.startswith("Baseline") else ''),("Scenarios","/workspace/scenarios",''),("Policies","/workspace/policies",''),("Capacity","/workspace/capacity",''),("Vault","/workspace/vault",'')])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} · Locust Performance Kit</title><link rel="stylesheet" href="/assets/workspace.css"><script src="/assets/workspace.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header><span class="mark">LP</span><div><strong>Locust Performance Kit</strong><small>Local workspace</small></div></header><div class="shell"><nav aria-label="Workspace">{nav}</nav><main id="main"{' tabindex="-1"' if focus else ''}>{body}</main></div></body></html>'''
def inbox(rows:list[dict[str,Any]], q:dict[str,str], error:str="")->str:
    alert=f'<div class="alert danger" role="alert" tabindex="-1"><strong>Could not load runs.</strong> {e(error)} <a href="/workspace/runs">Retry</a></div>' if error else ''
    filters=f'''<form class="toolbar" method="get"><label>Search<input name="q" value="{e(q.get('q'))}"></label><label>Environment<input name="environment" value="{e(q.get('environment'))}"></label><label>Branch<input name="branch" value="{e(q.get('branch'))}"></label><label>Decision<select name="decision"><option value="">All</option>{''.join(f'<option {"selected" if q.get("decision")==x else ""}>{x}</option>' for x in ("PASS","FAIL","ADVISORY","ERROR"))}</select></label><button>Apply filters</button><a class="button" href="/workspace/runs">Clear</a></form>'''
    if not rows:
        content='''<section class="hero"><p class="eyebrow">LOCAL-FIRST PERFORMANCE DECISIONS</p><h2>Turn a Locust run into an explainable decision</h2><p>Import evidence, compare it with a baseline, and export a reproducible decision. Files stay on this host.</p><div class="actions"><a class="button primary" href="/workspace/runs/import">Import run</a><a class="button" href="/workspace/sample">Try sample run</a></div><pre>locust --headless --csv results</pre></section>'''
    else:
        trs=''.join(f'<tr><th scope="row"><a href="/workspace/runs/{e(r["id"])}">{e(r["label"])}</a></th><td><span class="badge {e(r["decision"].lower())}">{e(r["decision"])}</span></td><td>{e(r["environment"])}</td><td>{e(r["branch"])}</td><td>{e(r["quality_grade"])}</td></tr>' for r in rows)
        content=f'<div class="table-wrap" tabindex="0"><table><caption>{len(rows)} runs</caption><thead><tr><th>Run</th><th>Decision</th><th>Environment</th><th>Branch</th><th>Quality</th></tr></thead><tbody>{trs}</tbody></table></div>'
    body=f'''<div class="heading"><div><p class="eyebrow">Performance workspace</p><h1>Runs</h1><p>Recent source-linked performance decisions.</p></div><a class="button primary" href="/workspace/runs/import">Import run</a></div>{alert}{filters}{content}'''
    return shell("Runs",body)
def import_form(error:str="")->str:
    alert=f'<div id="errors" class="alert danger" role="alert" tabindex="-1"><strong>Import failed.</strong> {e(error)}</div>' if error else ''
    body=f'''<p><a href="/workspace/runs">Runs</a> / Import</p><h1>Import a Locust run</h1><div class="alert info">Files are processed on this host. No data is sent externally.</div>{alert}<form method="post" enctype="multipart/form-data" action="/workspace/runs/import/validate"><label for="archive">Result ZIP</label><div class="drop"><input id="archive" name="archive" type="file" accept=".zip" required><p>Choose or drop one ZIP, up to 100 MiB.</p></div><button class="primary">Validate run</button> <a class="button" href="/workspace/runs">Cancel</a></form>'''
    return shell("Import run",body,focus=bool(error))
def preview(session_id:str,candidates:list[Any],error:str="")->str:
    opts=''.join(f'<label class="candidate"><input type="radio" name="candidate" value="{i}" {"checked" if len(candidates)==1 else ""} required><strong>{e(c.prefix)}</strong><span>Quality {e(c.quality_grade)} · {c.endpoint_count} endpoints · {c.history_samples} history samples</span></label>' for i,c in enumerate(candidates))
    body=f'''<p><a href="/workspace/runs">Runs</a> / <a href="/workspace/runs/import">Import</a> / Review</p><h1>Review detected run</h1>{f'<div class="alert danger">{e(error)}</div>' if error else ''}<form method="post" action="/workspace/runs/import/commit"><input type="hidden" name="session_id" value="{e(session_id)}"><fieldset><legend>Detected candidate</legend>{opts}</fieldset><div class="form-grid"><label>Run label<input name="label" required maxlength="120" value="Imported Locust run"></label><label>Environment<input name="environment" maxlength="80"></label><label>Branch<input name="branch" maxlength="80"></label><label>P95 SLO (ms)<input name="p95" type="number" min="1" max="3600000"></label></div><button class="primary">Analyze run</button> <a class="button" href="/workspace/runs/import">Choose another file</a></form>'''
    return shell("Review import",body)
def detail(run:dict[str,Any])->str:
    d=run["report"]; findings=d.get("findings",[]); status=d["decision"]["status"]
    fhtml=''.join(f'<details><summary><span class="badge {e(x["severity"])}">{e(x["severity"].upper())}</span> {e(x["message"])}</summary><dl><dt>Rule</dt><dd>{e(x["rule_id"])} v{e(x["rule_version"])}</dd><dt>Confidence</dt><dd>{e(x["confidence"])}</dd><dt>Next check</dt><dd>{e(x["next_check"])}</dd></dl></details>' for x in findings) or '<p>No anomalies were detected.</p>'
    summary=d.get("summary",{}); cards=''.join(f'<article><small>{e(k.replace("_"," ").title())}</small><strong>{e(v)}</strong></article>' for k,v in list(summary.items())[:6])
    eligible=status in {"PASS","ADVISORY"} and not run["sample"]
    promote=f'<a class="button" href="/workspace/baselines/promote?run_id={e(run["id"])}">Promote as baseline</a>' if eligible else '<p class="muted">Only verified PASS or explicitly overridden ADVISORY runs can be promoted.</p>'
    body=f'''<p><a href="/workspace/runs">Runs</a> / {e(run["label"])}</p><div class="heading"><div><h1>{e(run["label"])}</h1><p>{e(run["environment"])} · {e(run["branch"])} · quality {e(run["quality_grade"])}</p></div><div class="actions"><a class="button primary" href="/workspace/runs/{e(run["id"])}/decision.json">Download decision JSON</a><a class="button" href="/workspace/runs/{e(run["id"])}/summary.md">Download Markdown</a></div></div><section class="decision {e(status.lower())}"><p>Measured decision</p><strong>{e(status)}</strong></section><section><h2>Run summary</h2><div class="metrics">{cards}</div></section><section><h2>Findings and evidence</h2>{fhtml}</section><section><h2>Provenance</h2><p>Decision hash <code>{e(d["hash"]["value"])}</code></p>{promote}</section>'''
    return shell(f"{status} · {run['label']}",body,focus=True)
def baselines(rows:list[dict[str,Any]])->str:
    cards=''.join(f'<article><span class="badge {e(r["state"].lower())}">{e(r["state"])}</span><h2>{e(r["environment"])}</h2><p>{e(r["label"])}</p><a href="/workspace/runs/{e(r["run_id"])}">View run</a></article>' for r in rows) or '<section class="empty"><h2>No baselines yet</h2><p>Promote a verified passing run from Run Detail.</p><a href="/workspace/runs?decision=PASS">Find passing runs</a></section>'
    return shell("Baselines",f'<h1>Baselines</h1><p>One active, immutable reference per environment.</p><section class="cards">{cards}</section>')
def promote_form(run:dict[str,Any],error:str="")->str:
    advisory=run["decision"]=="ADVISORY"
    body=f'''<p><a href="/workspace/baselines">Baselines</a> / Promote</p><h1>Promote baseline</h1>{f'<div class="alert danger">{e(error)}</div>' if error else ''}<article><strong>{e(run["label"])}</strong><p>{e(run["decision"])} · Quality {e(run["quality_grade"])}</p></article><form method="post"><input type="hidden" name="run_id" value="{e(run["id"])}"><label>Environment<input name="environment" required maxlength="80"></label><label>Baseline label<input name="label" required maxlength="120" value="{e(run["label"])}"></label><label>Reason<textarea name="reason" required minlength="{20 if advisory else 10}"></textarea></label>{'<label><input type="checkbox" name="allow_advisory" value="1"> Explicitly allow this advisory result</label>' if advisory else ''}<button class="primary">Promote baseline</button> <a class="button" href="/workspace/runs/{e(run["id"])}">Cancel</a></form>'''
    return shell("Promote baseline",body)
